### ISSUE TITLE
problem with play m3u8 video, can not be played.

### ISSUE THREAD

**Issue by qianguozheng** [squid-cache/squid#13]
I am in China, so maybe you cannot reproduce the problem, I access m.youku.com on mobile through squid as a transparent proxy, however, the video often could not be played on browser.

I have searched this problem for a long time,  just found out that the mediaserver on mobile may work different. 

So, anyone encounter such problem ? or have any suggestion ?

**Comment by rousskov** [comment]
I am sorry that nobody has responded to your question for so long. The Squid Project does _not_ use Github Issues for support. We left this interface available by mistake, and we will be closing it down shortly, to avoid similar neglected issues in the future.

If you are still having a problem and need support, please post to the squid-users mailing [list](http://www.squid-cache.org/Support/mailing-lists.html#squid-users) or use other support [avenues](http://www.squid-cache.org/Support/).
