### ISSUE TITLE
crashed squid

### ISSUE THREAD

**Issue by catroot** [squid-cache/squid#15]
squid 4.0.16 process died with:

2016/11/23 09:28:04 kid1|         0 Duplicate URLs purged.
2016/11/23 09:28:04 kid1|         0 Swapfile clashes avoided.
2016/11/23 09:28:04 kid1|   Took 0.14 seconds (65848.93 objects/sec).
2016/11/23 09:28:04 kid1| Beginning Validation Procedure
2016/11/23 09:28:04 kid1|   Completed Validation Procedure
2016/11/23 09:28:04 kid1|   Validated 9076 Entries
2016/11/23 09:28:04 kid1|   store_swap_size = 206612.00 KB
2016/11/23 09:28:04 kid1| WARNING: Cannot retrieve '87.250.250.12:443'.
2016/11/23 09:28:04 kid1| assertion failed: FwdState.cc:268: "!EBIT_TEST(entry->flags, ENTRY_FWD_HDR_WAIT)"
2016/11/23 09:28:05| removing PID file: /var/run/squid.pid

**Comment by yadij** [comment]
I believe this is [bug 4529](http://bugs.squid-cache.org/show_bug.cgi?id=4529) which was fixed in the 4.0.17 release.
