### ISSUE TITLE
issue in src/client_side_request.cc

### ISSUE THREAD

**Issue by twoofy** [squid-cache/squid#16]
Hello,

This is my first time looking at the squid code.  I'm trying to debug a situation where squid 3.4 would return a ERR_ACCESS_DENIED and version 3.5 does not.   I believe its somehow related to ssl peek/slice/bump, but being new to Squid I can't really understand that too well.

So, I started looking at the source code between 3.4 and 3.5.  In 3.5 there is this code in src/client_side_request.cc.

```
    if (calloutContext->error) {
        const char *storeUri = request->storeId();
        StoreEntry *e= storeCreateEntry(storeUri, storeUri, request->flags, request->method);
#if USE_OPENSSL
        if (sslBumpNeeded()) { 
            // We have to serve an error, so bump the client first.
            sslBumpNeed(Ssl::bumpClientFirst);
            // set final error but delay sending until we bump 
            Ssl::ServerBump *srvBump = new Ssl::ServerBump(request, e);
            errorAppendEntry(e, calloutContext->error);
            calloutContext->error = NULL; 
            getConn()->setServerBump(srvBump);
            e->unlock("ClientHttpRequest::doCallouts+sslBumpNeeded");
        } else  
#endif
        {       
            // send the error to the client now
            clientStreamNode *node = (clientStreamNode *)client_stream.tail->prev->data;
            clientReplyContext *repContext = dynamic_cast<clientReplyContext *>(node->data.getRaw());
            assert (repContext);
            repContext->setReplyToStoreEntry(e, "immediate SslBump error");
            errorAppendEntry(e, calloutContext->error);
            calloutContext->error = NULL; 
            if (calloutContext->readNextRequest && getConn())
                getConn()->flags.readMore = true; // resume any pipeline reads.
            node = (clientStreamNode *)client_stream.tail->data;
            clientStreamRead(node, this, node->readBuffer);
            e->unlock("ClientHttpRequest::doCallouts-sslBumpNeeded");
            return; 
        }       
    }

```
If I change:

` if (sslBumpNeeded()) { 
`
to 

` if (sslBumpNeeded() && 0) { 
`
Then it correctly responds with ERR_ACCESS_DENIED.  Otherwise it seems to proceed along and actually process and return the request.

I sincerely apologize for not, yet, being able to get my head around this new feature.  But, it does seem like somehow calloutContext->error is getting lost or overridden by something else later in the processing chain.

Any ideas?

- Greg

**Comment by rousskov** [comment]
Please use the squid-users mailing list for Squid support. Very few people monitor these github issues...

When you post to squid-users, do mention whether you have configured SslBump. It is off by default. Posting your sanitized config is often the best strategy.

**Comment by rousskov** [comment]
I hope your question was resolved on squid-users. We will be closing Github Issues interface down shortly, to avoid similar neglected issues in the future. I am closing this issue.

If you are still having a problem and need support, please post to the squid-users mailing [list](http://www.squid-cache.org/Support/mailing-lists.html#squid-users) or use other support [avenues](http://www.squid-cache.org/Support/).
