### ISSUE TITLE
SRV record priority not honered.

### ISSUE THREAD

**Issue by thctlo** [squid-cache/squid#17]
Hai, 

Environment: Debian Jessie, Squid 3.5.24 debian rebuild from debian stretch.
kerberos_ldap_group: INFO: Starting version 1.3.1sq

The kerberos group goes wrong somewhere. 

a check on the SRV records shows. 
dig SRV _ldap._tcp.internal.domain.tld.

;; ANSWER SECTION:
_ldap._tcp.internal.domain.tld. 900 IN  SRV     5 100 636 dc1.internal.domain.tld.
_ldap._tcp.internal.domain.tld. 900 IN  SRV     5 100 636 dc2.internal.domain.tld.
_ldap._tcp.internal.domain.tld. 900 IN  SRV     10 100 389 dc1.internal.domain.tld.
_ldap._tcp.internal.domain.tld. 900 IN  SRV     10 100 389 dc2.internal.domain.tld.
;; AUTHORITY SECTION:

but debug logs shows. 

support_resolv.cc(407): pid=15718 :2017/02/20 08:24:03| kerberos_ldap_group: DEBUG: Adding internal.domain.tld to list
support_resolv.cc(443): pid=15718 :2017/02/20 08:24:03| kerberos_ldap_group: DEBUG: Sorted ldap server names for domain INTERNAL.DOMAIN.TLD:
support_resolv.cc(445): pid=15718 :2017/02/20 08:24:03| kerberos_ldap_group: DEBUG: Host: dc1.internal.domain.tld Port: 636 Priority: 5 Weight: 100
support_resolv.cc(445): pid=15718 :2017/02/20 08:24:03| kerberos_ldap_group: DEBUG: Host: dc2.internal.domain.tld Port: 389 Priority: 5 Weight: 100
support_resolv.cc(445): pid=15718 :2017/02/20 08:24:03| kerberos_ldap_group: DEBUG: Host: dc1.internal.domain.tld Port: 636 Priority: 10 Weight: 100
support_resolv.cc(445): pid=15718 :2017/02/20 08:24:03| kerberos_ldap_group: DEBUG: Host: dc2.internal.domain.tld Port: 389 Priority: 10 Weight: 100

Wrong order in the debug output.

**Comment by rousskov** [comment]
I am sorry that nobody has responded to your question for so long. The Squid Project does _not_ use Github Issues for support. We left this interface available by mistake, and we will be closing it down shortly, to avoid similar neglected issues in the future.

If you are still having a problem and need support, please post to the squid-users mailing [list](http://www.squid-cache.org/Support/mailing-lists.html#squid-users) or use other support [avenues](http://www.squid-cache.org/Support/).
