### ISSUE TITLE
Squid proxy does not retry on "connection refused"

### ISSUE THREAD

**Issue by style95** [squid-cache/squid#23]
I am using `sameersbn/squid:3.3.8-23` docker images.
I enabled this option: [connect_retries](http://www.squid-cache.org/Doc/config/connect_retries/)

It looks that squid retry when connection attempts fails with `No route to host`, but it does not retry on `Connection refused`

Difference between the two is, `No route to host` is the case that backend server is not ready(IP does not exist on network yet).
But `Connection refused` is the case that server is ready, but port is not exposed yet.

Isn`t it supposed to retry on both the cases?

**Comment by rousskov** [comment]
Squid v3.3 is not a supported release. The Squid Project does not use Github for support (yet).

You did the right thing by [posting](http://lists.squid-cache.org/pipermail/squid-users/2017-May/015290.html) this question to the squid-users mailing list. If nobody answers there, please consider reposting after retesting with Squid v3.5 or later.

**Comment by style95** [comment]
Thanks.
But before reporting this issue, I already tested with squid 3.5 and 4.
Same error occurred.
And I already posted on squid-users mailing list also.
No one has responded.

**Comment by rousskov** [comment]
> I already posted on squid-users mailing list

IIRC, your post said v3.3. If I am right, then you should repost to say v3.5 and v4. Posting a single transaction trace (from v3.5 or v4) may be very helpful as well: http://wiki.squid-cache.org/SquidFaq/BugReporting#Debugging_a_single_transaction
