### ISSUE TITLE
Multiple definition of base64_encode when statically linking with GnuTLS

### ISSUE THREAD

**Issue by joerg-krause** [squid-cache/squid#8]
Both GnuTLS and SQUID (Version 3.5.15) export a `base64_encode()` function leading to a symbol name clash when SQUID is linked statically with GnuTLS:

```
/usr/lib/libgnutls.a(base64.o): In function `base64_encode':
base64.c:(.text+0x14c): multiple definition of `base64_encode'
../../lib/.libs/libmiscencoding.a(base64.o):base64.c:(.text+0x204): first defined here
collect2: error: ld returned 1 exit status
Makefile:883: recipe for target 'squidclient' failed
make[4]: *** [squidclient] Error 1
```

A complete log of the build error: http://autobuild.buildroot.net/results/7b9/7b9387713177e40759f9b50b32badfc1a64ee5a6/build-end.log

**Comment by yadij** [comment]
I believe this issue is fixed in Squid-4. When the Nettle library (used by GnuTLS) is detected as present during builds Squid-4 will not define base64 and other crypto functionality itself, but will rely on linkage to the GnuTLS or Nettle library implementation.
